[
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "verificador_categoria_saude_address",
				"type": "address"
			}
		],
		"stateMutability": "nonpayable",
		"type": "constructor"
	},
	{
		"inputs": [
			{
				"internalType": "uint16",
				"name": "categoria_profissional_id",
				"type": "uint16"
			}
		],
		"name": "categoriaSaudeNaoExiste",
		"type": "error"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "admin",
				"type": "address"
			},
			{
				"internalType": "address",
				"name": "sender",
				"type": "address"
			}
		],
		"name": "isNotAdmin",
		"type": "error"
	},
	{
		"inputs": [],
		"name": "tipoProcedimentoLimiteAtingido",
		"type": "error"
	},
	{
		"inputs": [
			{
				"internalType": "uint16",
				"name": "tipo_procedimento_id",
				"type": "uint16"
			}
		],
		"name": "tipoProcedimentoNaoExiste",
		"type": "error"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "uint16",
				"name": "id",
				"type": "uint16"
			},
			{
				"indexed": false,
				"internalType": "string",
				"name": "tipo",
				"type": "string"
			},
			{
				"indexed": false,
				"internalType": "uint16",
				"name": "categoria_profissional_id",
				"type": "uint16"
			}
		],
		"name": "TipoCadastrado",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "uint16",
				"name": "id",
				"type": "uint16"
			},
			{
				"indexed": false,
				"internalType": "string",
				"name": "tipo",
				"type": "string"
			},
			{
				"indexed": false,
				"internalType": "uint16",
				"name": "categoria_profissional_id",
				"type": "uint16"
			}
		],
		"name": "TipoDeletado",
		"type": "event"
	},
	{
		"inputs": [
			{
				"internalType": "string",
				"name": "tipo",
				"type": "string"
			},
			{
				"internalType": "uint16",
				"name": "categoria_profissional_id",
				"type": "uint16"
			}
		],
		"name": "cadastraTipo",
		"outputs": [
			{
				"components": [
					{
						"internalType": "uint16",
						"name": "id",
						"type": "uint16"
					},
					{
						"internalType": "string",
						"name": "tipo",
						"type": "string"
					},
					{
						"internalType": "uint16",
						"name": "categoria_profissional_id",
						"type": "uint16"
					},
					{
						"internalType": "bool",
						"name": "cadastrado",
						"type": "bool"
					}
				],
				"internalType": "struct Entidades.TipoProcedimento",
				"name": "",
				"type": "tuple"
			}
		],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint16",
				"name": "id",
				"type": "uint16"
			}
		],
		"name": "deleteTipo",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint16",
				"name": "id",
				"type": "uint16"
			}
		],
		"name": "getTipo",
		"outputs": [
			{
				"components": [
					{
						"internalType": "uint16",
						"name": "id",
						"type": "uint16"
					},
					{
						"internalType": "string",
						"name": "tipo",
						"type": "string"
					},
					{
						"internalType": "uint16",
						"name": "categoria_profissional_id",
						"type": "uint16"
					},
					{
						"internalType": "bool",
						"name": "cadastrado",
						"type": "bool"
					}
				],
				"internalType": "struct Entidades.TipoProcedimento",
				"name": "",
				"type": "tuple"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint16",
				"name": "procedimento_id",
				"type": "uint16"
			}
		],
		"name": "verificarTipoProcedimento",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	}
]